[package]
name = "rustrace"
version = "0.1.0"
authors = ["Mason Clayton <masongclayton@gmail.com>"]

[[bin]]
name = "rustrace"

[dependencies]
num = "*"
image = "*"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
